### ISSUE TITLE
Link to message of attachment

### ISSUE THREAD

**Issue by radu81** [Spuds/Elk-Smush.it#1]
/index.php?action=admin;area=manageattachments;sa=smushitbrowse
There is a small bug when I browse attachments from this addon, if I click to the message where attachment is saved it brings me on the first message of the discussion
example:
index.php?topic=5731.0.msg94064#msg94064
should be
index.php?topic=5731.msg94064#msg94064

**Comment by Spuds** [comment]
Thanks, I'll take a look !

**Comment by Spuds** [comment]
https://github.com/Spuds/Elk-Smush.it/commit/ee6245ea02f347fe1e5cddfb2c7ef6ab8f456aba
